export const FeaturedProductsData = [
  {
    _id: 1001,
    img: "https://images.pexels.com/photos/1055691/pexels-photo-1055691.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Long Sleeve Graphic T-shirt",
    isNew: true,
    oldPrice: 20,
    price: 15,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
  {
    _id: 1002,
    img: "https://images.pexels.com/photos/1972115/pexels-photo-1972115.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "T-shirt",
    isNew: true,
    oldPrice: 30,
    price: 25,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
  {
    _id: 1003,
    img: "https://images.pexels.com/photos/1375849/pexels-photo-1375849.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Shorts",
    isNew: false,
    oldPrice: 80,
    price: 70,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
  {
    _id: 1004,
    img: "https://images.pexels.com/photos/1457983/pexels-photo-1457983.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Coat",
    isNew: false,
    oldPrice: 60,
    price: 40,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
];

export const TrendingProductsData = [
  {
    _id: 2001,
    img: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=600",
    img2: "https://images.pexels.com/photos/206434/pexels-photo-206434.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Long Sleeve Graphic T-shirt",
    isNew: true,
    oldPrice: 20,
    price: 15,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
  {
    _id: 2002,
    img: "https://images.pexels.com/photos/884979/pexels-photo-884979.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "T-shirt",
    isNew: true,
    oldPrice: 30,
    price: 25,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
  {
    _id: 2003,
    img: "https://images.pexels.com/photos/1375849/pexels-photo-1375849.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    title: "Shorts",
    isNew: false,
    oldPrice: 80,
    price: 70,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
  {
    _id: 2004,
    img: "https://images.pexels.com/photos/1457983/pexels-photo-1457983.jpeg?auto=compress&cs=tinysrgb&w=600",
    title: "Coat",
    isNew: false,
    oldPrice: 60,
    price: 40,
    desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Harum cum ratione nihil vitae ex unde, perferendis fuga delectus quia saepe doloribus,",
  },
];
